main:
	g++ algorithms.cpp main.cpp interface.cpp algs_2.cpp matrix/matrix.cpp -lstdc++fs

ham:
	g++ hamming_algo.cpp matrix/matrix.cpp hamming_main.cpp cycle_polynom.cpp interface.cpp -lstdc++fs

ex:
	g++ hamming_algo.cpp matrix/matrix.cpp ex.cpp cycle_polynom.cpp interface.cpp -lstdc++fs
	